theme: jekyll-theme-minimal
title: Designing Accessible VR Experiences
description: A Panel on VR Accessibility and 3D Virtual Tour in Mozilla Hubs
logo: https://pretalx.com/media/mozfest-2021/submissions/MJWAMG/vr-accessibility_AUz8WJT.png
